# -*- coding: utf-8 -*-
"""testando_pacote_processamento_imagens.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gosML_s3Eu5FfqJamEeXV0Q0MflWCVpW

## Testando Pacote de Processamento de Imagens

Este código tem por objetivo testar o pacote de processamento de imagens criado no Desafio de Projeto: Descomplicando a criação de pacotes de processamento de imagens em Python.

Este projeto está inserido no BootCamp Ciência de dados - Unimed-BH da DIO.
"""

# Importando algumas bibliotecas
import pandas as pd # Pandas
import matplotlib as plt # Matplotlib
import numpy as np # Numpy
import skimage # Scikit-Image

# Instalando o pacote de processamento de imagens criado para o desafio
! pip install -i https://pypi.org/project/ dio-processador-imagens==0.0.2

# Importando os módulos a serem utilizados do pacote
from dio_processador_imagens.utils import io
from dio_processador_imagens.utils import plot
from dio_processador_imagens.processamento import combinacao, transformacao

# Lendo as imagens a serem processadas
laranjas = io.read_image("/content/drive/MyDrive/Bootcamp_DIO_Unimed-BH/imagens/pexels-dominika-roseclay-2090900.jpg")
morangos = io.read_image("/content/drive/MyDrive/Bootcamp_DIO_Unimed-BH/imagens/pexels-karolina-grabowska-4038787.jpg")

# Plotando as imagens
plot.plot_image(laranjas)
plot.plot_image(morangos)

# Colorindo laranjas com morangos
imagem_combinada = combinacao.transfer_histogram(laranjas, morangos)
plot.plot_result(laranjas, morangos, imagem_combinada)

# Colorindo morangos com laranjas
imagem_combinada2 = combinacao.transfer_histogram(morangos, laranjas)
plot.plot_result(morangos, laranjas, imagem_combinada2)

"""Agora é só exercitar a criatividade na combinação de cores de imagens!"""